version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: 2025portfolio
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-p1234']
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build: .
    container_name: nest-backend
    restart: always
    ports:
      - '3002:3002'
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - /app
    working_dir: /app
    command: npm run start:dev

volumes:
  mysql-data:
